// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr48l03uFnXUhXpgQHGhRqaJnd06wt9w0',
    appId: '1:488341355430:web:a2a76117d5923b07db6d67',
    messagingSenderId: '488341355430',
    projectId: 'equalride-group11',
    authDomain: 'equalride-group11.firebaseapp.com',
    storageBucket: 'equalride-group11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCZZumCwIfK7XfJaY-ThT_fFed0SIO6r4',
    appId: '1:488341355430:android:a3972a1fdbf3a621db6d67',
    messagingSenderId: '488341355430',
    projectId: 'equalride-group11',
    storageBucket: 'equalride-group11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYrOspiGbfCjeYUwHzFSaGtu1RJQZ8anc',
    appId: '1:488341355430:ios:90d846caa56aa7b3db6d67',
    messagingSenderId: '488341355430',
    projectId: 'equalride-group11',
    storageBucket: 'equalride-group11.firebasestorage.app',
    iosBundleId: 'com.example.equalDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYrOspiGbfCjeYUwHzFSaGtu1RJQZ8anc',
    appId: '1:488341355430:ios:90d846caa56aa7b3db6d67',
    messagingSenderId: '488341355430',
    projectId: 'equalride-group11',
    storageBucket: 'equalride-group11.firebasestorage.app',
    iosBundleId: 'com.example.equalDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr48l03uFnXUhXpgQHGhRqaJnd06wt9w0',
    appId: '1:488341355430:web:0881f754b6df6a45db6d67',
    messagingSenderId: '488341355430',
    projectId: 'equalride-group11',
    authDomain: 'equalride-group11.firebaseapp.com',
    storageBucket: 'equalride-group11.firebasestorage.app',
  );
}
